---
- name: Gather facts from all hosts
  hosts: patch_seso_2025
  gather_facts: yes
  tasks:
    - name: Debug host facts
      ansible.builtin.debug:
        msg: "Gathered facts for {{ inventory_hostname }}"

- name: Publish Inventory to Confluence Cloud
  hosts: localhost
  gather_facts: false
  vars:
    confluence_base_url: "https://nareshyadavmusic.atlassian.net/wiki"
    confluence_space: "aap"
    page_title: "AAP Inventory - {{ target_group | default('all') }}"
    target_group: all
  tasks:
    - name: Load Confluence credentials from environment
      set_fact:
        confluence_user: "{{ lookup('env', 'CONFLUENCE_USER') }}"
        confluence_token: "{{ lookup('env', 'CONFLUENCE_TOKEN') }}"

    - name: Validate Confluence credentials
      ansible.builtin.fail:
        msg: "Confluence credentials not set correctly"
      when: confluence_user == "" or confluence_token == ""

    - name: Check if Confluence page exists
      ansible.builtin.uri:
        url: "{{ confluence_base_url }}/rest/api/content?title={{ page_title | urlencode }}&spaceKey={{ confluence_space }}&expand=version"
        user: "{{ confluence_user }}"
        password: "{{ confluence_token }}"
        force_basic_auth: yes
        status_code: 200
        return_content: yes
      register: confluence_page_check

    - name: Set page ID and version if found
      set_fact:
        existing_page_id: "{{ confluence_page_check.json.results[0].id | default('') }}"
        existing_version: "{{ confluence_page_check.json.results[0].version.number | default(0) }}"
      when: confluence_page_check.json.results | length > 0

    - name: Determine safe target group
      set_fact:
        safe_group_name: "{{ target_group if (target_group in groups) else 'all' }}"
      run_once: true

    - name: Build Confluence Storage table with inventory data
      set_fact:
        table_html: "{{ lookup('template', 'inventory_table_confluence.j2') }}"
      vars:
        group_name: "{{ safe_group_name }}"
      run_once: true

    - name: Prepare Confluence body (storage format)
      set_fact:
        confluence_body: >-
          {{
            {
              "type": "page",
              "title": page_title,
              "space": {"key": confluence_space},
              "body": {
                "storage": {
                  "value": table_html,
                  "representation": "storage"
                }
              },
              "version": {"number": (existing_version | int) + 1}
            }
          }}

    - name: Create or update Confluence page
      ansible.builtin.uri:
        url: >-
          {{ confluence_base_url }}/rest/api/content{{ '/' + existing_page_id if existing_page_id | length > 0 else '' }}
        method: "{{ 'PUT' if existing_page_id | length > 0 else 'POST' }}"
        user: "{{ confluence_user }}"
        password: "{{ confluence_token }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ confluence_body }}"
        status_code: [200, 201]