---
- name: Check host reachability and gather facts
  hosts: patch_seso_2025
  gather_facts: false
  tasks:
    - name: Ping test
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: true

    - name: Set reachability status
      ansible.builtin.set_fact:
        reachable_status: "{{ 'reachable' if ping_result.ping is defined else 'unreachable' }}"

- name: Gather facts from reachable hosts
  hosts: patch_seso_2025
  gather_facts: yes
  tasks:
    - name: Skip unreachable hosts
      ansible.builtin.meta: end_host
      when: hostvars[inventory_hostname].reachable_status == 'unreachable'

- name: Update Confluence page with latest inventory
  hosts: localhost
  gather_facts: false
  vars:
    confluence_base_url: "https://nareshyadavmusic.atlassian.net/wiki"
    confluence_space: "aap"
    page_title: "AAP Inventory - patch_seso_2025"
    safe_group_name: "patch_seso_2025"
  tasks:
    - name: Load Confluence credentials from environment
      ansible.builtin.set_fact:
        confluence_user: "{{ lookup('env', 'CONFLUENCE_USER') }}"
        confluence_token: "{{ lookup('env', 'CONFLUENCE_TOKEN') }}"

    - name: Validate credentials
      ansible.builtin.fail:
        msg: "Confluence credentials not set correctly"
      when: confluence_user | length == 0 or confluence_token | length == 0

    - name: Check if Confluence page exists
      ansible.builtin.uri:
        url: "{{ confluence_base_url }}/rest/api/content?title={{ page_title | urlencode }}&spaceKey={{ confluence_space }}&expand=version"
        user: "{{ confluence_user }}"
        password: "{{ confluence_token }}"
        force_basic_auth: yes
        method: GET
        status_code: 200
        return_content: yes
      register: confluence_page_check

    - name: Set page ID and version if found
      ansible.builtin.set_fact:
        existing_page_id: "{{ confluence_page_check.json.results[0].id | default('') }}"
        existing_version: "{{ confluence_page_check.json.results[0].version.number | default(0) }}"
      when: confluence_page_check.json.results | length > 0

    - name: Ensure defaults for Confluence page facts
      ansible.builtin.set_fact:
        existing_page_id: "{{ existing_page_id | default('') }}"
        existing_version: "{{ existing_version | default(0) }}"

    - name: Build table for Confluence
      ansible.builtin.set_fact:
        table_html: "{{ lookup('template', 'inventory_table_confluence.j2') }}"
      vars:
        group_name: "{{ safe_group_name }}"

    - name: Prepare body for update
      ansible.builtin.set_fact:
        confluence_body: >-
          {{
            {
              "id": existing_page_id,
              "type": "page",
              "title": page_title,
              "space": {"key": confluence_space},
              "version": {"number": (existing_version | int) + 1},
              "body": {
                "storage": {
                  "value": table_html,
                  "representation": "storage"
                }
              }
            }
          }}

    - name: Update existing Confluence page
      ansible.builtin.uri:
        url: "{{ confluence_base_url }}/rest/api/content/{{ existing_page_id }}"
        method: PUT
        user: "{{ confluence_user }}"
        password: "{{ confluence_token }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ confluence_body }}"
        status_code: [200, 201]
      when: existing_page_id | length > 0